server:
  port: 8760
  servlet:
    context-path:
spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    user:     #路由名称
      path: /user/**
      serviceId: user #微服务名称
      strip-prefix: true
      sensitiveHeaders:   #cookie
      ignoredHeaders:    #头信息
    auth:     #路由名称
      path: /auth/**
      serviceId: auth #微服务名称
      strip-prefix: true
      sensitiveHeaders:   #cookie
      ignoredHeaders:    #头信息
    web:     #路由名称
      path: /web/**
      serviceId: web #微服务名称
      strip-prefix: true
      sensitiveHeaders:   #cookie
      ignoredHeaders:    #头信息
security:
  oauth2:
    client:
       ##网关的地址
      access-token-uri: http://localhost:8760/auth/oauth/token
      user-authorization-uri: http://localhost:8760/auth/oauth/authorize
      client-id: gateway
      client-secret: 123456
    resource:
      user-info-uri: http://localhost:8760/auth/user
      prefer-token-info: false
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
    authorization:
      check-token-access: http://localhost:8760/auth/oauth/check_token