server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://39.102.34.165:8761/eureka/
spring:
  application:
    name: auth
#数据源
  datasource:
      name: test
      url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#redis配置
  redis:
      host: 39.102.34.165
      port: 6379
      jedis:
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
      password: 123456
  boot:
      admin:
        client:
          url: "http://39.102.34.165:8369"
management:
  endpoints:
    web:
      exposure:
        include: "*"