server:
  port: 8766

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://39.102.34.165:8761/eureka/
spring:
  application:
    name: file
  #数据源
  datasource:
      name: test
      url: jdbc:mysql://39.102.34.165:3306/abs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  zipkin:
    base-url: http://39.102.34.165:9411
  sleuth:
    sampler:
      probability: 0.5
  boot:
    admin:
      client:
        url: "http://39.102.34.165:8369"
management:
  endpoints:
    web:
      exposure:
        include: "*"

